{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildgrid.fullname" . }}-redis
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "buildgrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.master.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "buildgrid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
