{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildgrid.fullname" . }}-postgresql-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "buildgrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  superuser-password: {{ .Values.postgresql.auth.superuserPassword | b64enc | quote }}
{{- end }}
