apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildgrid.fullname" . }}-server
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "buildgrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.global.serviceType }}
  ports:
    - port: {{ .Values.buildgrid.server.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      {{- if eq .Values.global.serviceType "NodePort" }}
      nodePort: {{ .Values.buildgrid.server.nodePort | default 30051 }}
      {{- end }}
    {{- if .Values.monitoring.prometheus.enabled }}
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "buildgrid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
